site_name: Columbia Urdu Poetry Group
site_url: https://example.com/
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - tabs
    - search.suggest
    - search.share
    - search.highlight
    - header.autohide
plugins:
  - search
  - awesome-pages
  - tags:
      tags_file: tags.md
markdown_extensions:
  - meta
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - smarty
  - tables
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - attr_list
extra_css:
  - stylesheets/extra.css
