name: Deploy MkDocs
on:
  push:
    paths:
      - "docs/"
      - ".yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Generate Files
        env:
          DIRECTORY_PATH: ${{ github.workspace }}/docs/poets
          API_KEY: ${{secrets.AIRTABLE_API_KEY}}
        run: |
          echo "$GITHUB_WORKSPACE"
          python script.py --poets-dir-path "${DIRECTORY_PATH}"" --api-key "${API_KEY}"

# run: |
# git config user.name ${{ secrets.GH_USER }}
# git config user.email "${{ secrets.GH_MAIL }}"
# git remote add gh-token "https://${{ secrets.GH_TOKEN}}@github.com/:user/:repo.git"
# git fetch gh-token && git fetch gh-token gh-pages:gh-pages
# python -m mkdocs gh-deploy -v --clean --remote-name gh-token
# git push gh-token gh-pages
